name: Java CI

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v2

    - name: Instalar JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'


    - name: Descargar dependencias externas
      run: |
        mkdir -p lib
        curl -L -o lib/itextpdf-5.5.12.jar https://repo1.maven.org/maven2/com/itextpdf/itextpdf/5.5.12/itextpdf-5.5.12.jar
        curl -L -o lib/jcalendar-1.4.jar https://repo1.maven.org/maven2/net/sf/jcalendar/jcalendar/1.4/jcalendar-1.4.jar
        curl -L -o lib/mysql-connector-java-5.1.46.jar https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.46/mysql-connector-java-5.1.46.jar
        curl -L -o lib/AbsoluteLayout.jar https://repo1.maven.org/maven2/net/sf/absolutelayout/AbsoluteLayout/1.0/AbsoluteLayout-1.0.jar || echo "Descarga manual requerida"

    - name: Compilar proyecto
      run: |
        mkdir -p bin
        find Ventas/src -name "*.java" > sources.txt
        javac -cp "lib/*" -d bin @sources.txt

