name: Java CI

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v2

    - name: Instalar JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Descargar iTextPDF
      run: |
        mkdir -p lib
        curl -L -o lib/itextpdf-5.5.13.3.jar https://repo1.maven.org/maven2/com/itextpdf/itextpdf/5.5.13.3/itextpdf-5.5.13.3.jar

    - name: Compilar proyecto
      run: |
        mkdir -p bin
        find Ventas/src -name "*.java" > sources.txt
        javac -cp "lib/itextpdf-5.5.13.3.jar" -d bin @sources.txt
